# Generated by Django 5.1.15 on 2026-06-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period', models.CharField(default='one-time', help_text='e.g. one-time, 8 weeks, lifetime', max_length=30)),
                ('features', models.JSONField(blank=True, default=list, help_text="List of included mission features e.g. ['Full curriculum', 'Live relays']")),
                ('is_featured', models.BooleanField(default=False)),
                ('cta_label', models.CharField(default='Select Trajectory', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(default='Language Architect', max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('quote', models.CharField(blank=True, max_length=200)),
                ('accent_color', models.CharField(default='#00e5ff', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Crew Member',
                'verbose_name_plural': 'Crew',
                'ordering': ['order'],
            },
        ),
    ]
