# Generated by Django 5.1.15 on 2026-06-09 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('level', models.CharField(choices=[('A1', 'A1 — Entry Vector'), ('A2', 'A2 — Launch Vector'), ('B1', 'B1 — Stable Orbit'), ('B2', 'B2 — Deep Trajectory'), ('C1', 'C1 — Deep Space'), ('C2', 'C2 — Command Level')], default='A1', max_length=2)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Rich mission briefing. Supports Markdown.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=8)),
                ('format', models.CharField(choices=[('self_paced', 'Self-Paced Mission'), ('live_cohort', 'Live Cohort'), ('private', 'Private Command')], default='self_paced', max_length=20)),
                ('max_enrollments', models.PositiveSmallIntegerField(default=24, help_text='0 = unlimited')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('what_you_will_learn', models.JSONField(blank=True, default=list, help_text="List of objectives, e.g. ['Master 1200 words', ...]")),
                ('requirements', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='accounts.teacherprofile')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.language')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(choices=[('text', 'Transmission (Text/Markdown)'), ('video', 'Video Briefing'), ('mixed', 'Mixed')], default='text', max_length=10)),
                ('content', models.TextField(blank=True, help_text='Markdown or rich content for the lesson.')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo or hosted URL')),
                ('duration_min', models.PositiveSmallIntegerField(default=12)),
                ('is_preview', models.BooleanField(default=False, help_text='Available without enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
